EMovi/Models/Movie.cs
namespace EMovi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.ActsIns = new HashSet<ActsIn>();
            this.Directs = new HashSet<Direct>();
            this.Rates = new HashSet<Rate>();
            this.Genres = new HashSet<Genre>();
        }
    
        public int MovieId { get; set; }
        public string Name { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActsIn> ActsIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direct> Directs { get; set; }
        public virtual Poster Poster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genres { get; set; }
    }
}

EMovi/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMovi.Models;

namespace EMovi.Controllers
{
    public class MovieController : Controller
    {
        DatabaseEntities _db = new DatabaseEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Total(Movie movie) {

            var query = _db.Movies.Where(m => m.MovieId == movie.MovieId);

            return View(query.First());
        }

        [HttpGet]
        public ActionResult Search(string name = null, string genre = null, string year = null)
        {
            if (String.IsNullOrWhiteSpace(year)) year = null;
            if (String.IsNullOrWhiteSpace(name)) name = null;
            if (String.IsNullOrWhiteSpace(genre)) genre = null;            

            var query =
                _db.Movies
                .Where(
                    r =>
                    (name == null || r.Name.Contains(name)) &&
                    (year == null || r.ReleaseDate.Year.ToString().Equals(year)) &&
                    (genre == null || r.Genres.Any(g => g.Name.Equals(genre)))
                );


            return View(query);
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMovi/Controllers/PersonController.cs
using EMovi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EMovi.Controllers
{
    public class PersonController : Controller
    {

        DatabaseEntities _db = new DatabaseEntities();
        

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Total(Person person)
        {
            var query = _db.People.Where(p => p.PersonId == person.PersonId);
            var result = query.First();

            return View(result);
        }

        public ActionResult Search(string fname = null, string lname = null, string genre = null, string year = null, string typePerson = null)
        {
            if (String.IsNullOrWhiteSpace(year)) year = null;
            if (String.IsNullOrWhiteSpace(fname)) fname = null;
            if (String.IsNullOrWhiteSpace(lname)) lname = null;
            if (String.IsNullOrWhiteSpace(genre)) genre = null;
            if (String.IsNullOrWhiteSpace(typePerson)) typePerson = null;

            IQueryable<Person> query = null;

            if (typePerson == null)
            {
                query =
                        _db.People
                        .Where(person => (
                           (fname == null || person.FirstName.Contains(fname)) &&
                           (lname == null || person.LastName.Contains(lname)) &&
                           (genre == null || 
                                person.Actors.Any(actor => actor.ActsIns.Any(role => role.Movie.Genres.Any(g => g.Name.Contains(genre)))) ||
                                person.Directors.Any(director => director.Directs.Any(role => role.Movie.Genres.Any(g => g.Name.Contains(genre))))
                                )
                        ));
            }
            else if (typePerson.ToLower().Equals("actor"))
            {
                query =
                        _db.People
                        .Where(person => (
                           (person.Actors.Any(actor => _db.Actors.Any(a => a.ActorId == actor.ActorId ))) &&
                           (fname == null || person.FirstName.Contains(fname)) &&
                           (lname == null || person.LastName.Contains(lname)) &&
                           (genre == null || person.Actors.Any(actor => actor.ActsIns.Any(role => role.Movie.Genres.Any(g => g.Name.Contains(genre)))))
                        ));
            }
            else if (typePerson.ToLower().Equals("director"))
            {
                query =
                    _db.People
                    .Where(person => (
                        (person.Directors.Any(director => _db.Directors.Any(d => d.DirectorID == director.DirectorID))) &&
                        (fname == null || person.FirstName.Contains(fname)) &&
                        (lname == null || person.LastName.Contains(lname)) &&
                        (genre == null || person.Directors.Any(director => director.Directs.Any(role => role.Movie.Genres.Any(g => g.Name.Contains(genre)))))
                    ));
            }
            else if (typePerson.ToLower().Equals("both"))
            {
                query =
                        _db.People
                        .Where(person => (
                           (
                                (person.Directors.Any(director => _db.Directors.Any(d => d.DirectorID == director.DirectorID))) &&
                                (person.Actors.Any(actor => _db.Actors.Any(a => a.ActorId == actor.ActorId)))
                            ) &&

                           (fname == null || person.FirstName.Contains(fname)) &&
                           (lname == null || person.LastName.Contains(lname)) &&
                           (genre == null ||
                                person.Actors.Any(actor => actor.ActsIns.Any(role => role.Movie.Genres.Any(g => g.Name.Contains(genre)))) ||
                                person.Directors.Any(director => director.Directs.Any(role => role.Movie.Genres.Any(g => g.Name.Contains(genre))))
                                )
                        ));
            }

            return View(query);
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMovi/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Movies";
}
<header>
    <h1>Search by Movie</h1>
</header>
@using (Html.BeginForm("Search", "Movie", FormMethod.Get, new { id = "container" }))
{

    <div class="input_element">
        <p>Name:</p>
        <input type="text" name="name" placeholder="Name">
    </div>

    <div class="input_element">
        <p>Genres:</p>
        <input type="text" name="genre" placeholder="Genre">
    </div>

    <div class="input_element">
        <p>Year:</p>
        <input type="text" name="year" placeholder="Year">
    </div>

    <input id="search" type="submit" value="Search">
}

EMovi/Views/Movie/Search.cshtml
@model IEnumerable<EMovi.Models.Movie>

@{
    ViewBag.Title = "Search";
}
@if (!Model.Any())
{
    <h2 align="center" style="font-size:120px;">No Results Found</h2>
}
else
{

    <div id="container2">
        <table width="100%">

            @foreach (var movie in Model)
            {
                <!--template result for movie-->
                <tr class="result">
                    <td class="img">
                        <img src="@movie.Poster.PosterLink" />
                    </td>

                    <!--The sizes of the heading tags are arbitrary. i.e changing them will not break anything-->
                    <td class="info">
                        <h3>@Html.ActionLink(movie.Name, "Total", "Movie", movie, new { id = movie.Name })</h3>
                        @if (movie.Directs != null)
                        {
                            <h5>
                                Directed By: @foreach (var director in movie.Directs)
                                {
                                    @(director.Director.Person.FirstName + " " + director.Director.Person.LastName + ", ")
                                }
                            </h5>
                        }
                        <h5>
                            Genres: @foreach (var genre in movie.Genres)
                            {
                                @(genre.Name + ", ")
                            }
                        </h5>
                    </td>

                    @if (movie.Rates != null)
                    {

                        var total = 0;
                        var count = 0;
                        foreach (var rating in movie.Rates)
                        {
                            count++;
                            total += rating.Rating;
                        }

                        <td class="rating" width="25%">
                            <h3>Avg Rating:</h3>
                            <h4>@(total / count)</h4>
                        </td>
                    }
                </tr>
            }
        </table>
    </div>
}

EMovi/Views/Movie/Total.cshtml
@model EMovi.Models.Movie

@{
    ViewBag.Title = "Total";
}
<table img="display" id="container2">
    <tr>
        <td class="data-img">
            <img src="@Model.Poster.PosterLink" class="data-img2" />
        </td>

        <td class="details">
            <h1>@Model.Name </h1>
            <h4>
                Genre(s): @foreach (var genre in Model.Genres)
                {
                    @(genre.Name + ", ")
                }
            </h4>
            <h4>
                Directed By: @foreach (var director in Model.Directs)
                {
                    @Html.ActionLink(director.Director.Person.FirstName + " " + director.Director.Person.LastName + ", ", "Total", "Person", director.Director.Person, new { id = director })
                }
            </h4>
            <h4>
                Actors/Actresses: @foreach (var actor in Model.ActsIns)
                {
                    @Html.ActionLink(actor.Actor.Person.FirstName + " " + actor.Actor.Person.LastName + ", ", "Total", "Person", actor.Actor.Person, new { id = actor })
                }
            </h4>
            <p>
                @Model.Description
            </p>
            <h5>Date/Year Released: @Model.ReleaseDate.ToShortDateString()</h5>
            @{ 
                var total =0;
                var count =0;
                foreach (var rating in Model.Rates){
                    count++;
                    total += rating.Rating;
                }
            }
            <h5>Avg Rating: @(total/count)</h5>
        </td>
    </tr>
</table>